/* === Shared Public API: Start === */
window.AppUtils = {
	config: APP_CONFIG,
	formatDate,
	parseDate,
	normalizeSpreadsheetDate,
	isSameMonth,
	normalizeSN,
	normalizeSearchText,
	matchesSearchQuery,
	escapeHtml,
	formatDateTimeLabel,
	renderIcon,
	getInitials,
	normalizeAccessoryKey,
	normalizeAccessories,
	getSelectedAccessories,
	normalizeAuditFields,
	buildAuditMarkup,
	confirmDialog,
	renderAccessoryIcons,
	createMonthPicker,
	createSearchController,
	createAvatarMarkup,
	notify,
	auth: {
		getCurrentUser,
		isAuthenticated,
		isCurrentUserAdmin,
		isCurrentUserLeader,
		hasPermission,
		changePassword: changeCurrentUserPassword,
		updateUserAccess,
		getRoleLabel,
		getPermissionLabel,
		getPermissionOptions: () => [...AUTH_CONFIG.permissionOptions],
		getAuditActorSnapshot,
		getAuditActorLabel,
		openAuthModal,
		openProfileModal,
	},
}
/* === Shared Public API: End === */
